### ISSUE TITLE
index.php missing

### ISSUE THREAD

**Issue by RasikaEkanayake** [fahomid/Case-Management-System-Using-Laravel#3]
Warning: require_once(C:\Users\Compressed\Case-Management-System-Using-Laravel-main\Case-Management-System-Using-Laravel-main/public/index.php): Failed to open stream: No such file or directory in C:\Users\Compressed\Case-Management-System-Using-Laravel-main\Case-Management-System-Using-Laravel-main\server.php on line 21

**Comment by fahomid** [comment]
Install laravel first and then copy all the files provided here into your default installation directory. Default index.php file should work fine.
